---
- name: All arch hosts update
  hosts: arch
  gather_facts: yes
  become: yes

  tasks:
    - name: full system upgrade
      ansible.builtin.pacman:
        update_cache: yes
        upgrade: yes

    - name: check if reboot required
      ansible.builtin.script:
        cmd: /etc/ansible/scripts/check_reboot_required

    - name: register reboot
      ansible.builtin.stat:
        path: /var/run/reboot_required
      register: reboot_required_file

    - name: reboot when required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
