---
- name: All arch hosts update
  hosts: local
  gather_facts: true
  become: true

  tasks:
    - name: full system upgrade
      ansible.builtin.pacman:
        update_cache: yes
        upgrade: yes
